version: '2'
services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=resbook_db
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - /var/run/mysqld/mysqld.sock
    command: --innodb_use_native_aio=0
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true
    stdin_open: true
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/workdir
      